rogue-rabbits/grace-shopper

README.md
=> added Tristan in ReadMe

README.md
=> Svetlana branch

.travis.yml, package-lock.json, package.json, script/seed.js, server/api/index.js, server/api/products.js, server/api/users.js, server/db/models/index.js, server/db/models/product.js, server/db/models/user.js
=> Creating database models

client/components/AllProducts.js, client/components/Product.js, client/components/SingleProduct.js, client/components/index.js, client/components/navbar.js, client/routes.js, client/store/index.js, client/store/product.js
=> setup redux store and allproduct and singleproduct views

server/api/products.js
=> added express find by pk route

client/components/Product.js, client/components/SingleProduct.js, client/components/user-home.js, script/seed.js, server/db/models/cart.js, server/db/models/index.js
=> added cart database

client/components/Product.js, client/components/SingleProduct.js
=> added Price and $

client/components/SingleProduct.js, client/components/navbar.js, client/store/cart.js, server/api/cart.js
adding an item to the cart creates a new row in the cart table
=> Adding to cart

README.md
=> update readme with product info

client/store/cart.js, server/api/cart.js
The previous version of the feature was updating the quantity for all users. Now it updates the product quantity for the signed in user.
=> fix: update cart bug

client/components/Checkout.js, client/components/OrderConfirm.js, client/routes.js, client/store/orderHistory.js, script/seed.js, server/api/orderHistory.js, server/db/models/orderHistory.js
=> fix: updated order number generating functionality

server/db/models/user.js
=> fix:updated user model to pass test specs

.travis.yml
=> fix: updated heroku key

client/components/CartItem.js, client/components/user-home.js, client/store/cart.js
=> fix: update quantity in cart no longer throws an error

client/components/AllProducts.js, client/components/CartItem.js, client/components/Product.js, client/components/SingleProduct.js
Adds a new 'add to cart' button on the home page that adds one item to the cart
=> Add to cart all products

client/components/AllProducts.js, client/components/Product.js
=> fix: cart is updated from home page

client/components/navbar.js, package-lock.json, public/style.css
=> Add cart quantity

client/components/navbar.js
=> fix: adding overall cart quantity, not cart items only

client/components/Cart.js, client/components/CartItem.js, client/components/SingleProduct.js, client/components/navbar.js, client/components/user-home.js, client/components/user-home.spec.js, client/store/cart.js, server/api/cart.js, server/api/guestcart.js, server/api/index.js, server/api/orderHistory.js
=>  feat: guests can now add to cart and when they log in their cart will be saved to database

client/components/CartItem.js, client/components/Product.js, package-lock.json
=> feat: guest user can now add to cart from All Products view

client/components/CheckoutForm.js, public/style.css, server/db/models/cart.spec.js, server/db/models/orderHistory.js, server/db/models/orderHistory.spec.js, server/db/models/product.spec.js
=> fix:complete order only clickable once - test specs added

client/components/Product.js, client/components/product.spec.js, client/store/index.js
=> tests: Front end tests created

client/components/CartItem.js, public/style.css
=> Style: Styling fixes for background color

client/components/Cart.js, public/style.css
=> fix: checkout button disabled for empty cart

client/components/navbar.js
=> fix: cart quantity persists

client/components/auth-form.js, client/components/user-home.js
=> fix: revised order history information

client/components/Checkout.js, client/components/CheckoutForm.js, public/style.css
=> style: center complete order button
